version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-235-100-99.compute-1.amazonaws.com
            port: '5432'
            database: dpmm1bhpvp15f
            ssl: true
            user: xqflzxxrspimfy
            password: 2998694bda4f0a7e3dfed9298e82aa60de396fb1a953c7064e00da88c2378b20
            migrations: true
